- id: shell-cmd-on-change
  name: shell-cmd-on-change
  description: Run a shell command when certain files changed after a `git pull` or `git merge`.
  entry: ./bin/on-change.sh
  language: script
  pass_filenames: false
  stages: [post-merge]
  always_run: true
  verbose: true
